# Generated by Django 5.1.1 on 2024-10-11 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('406e9594-cf45-4453-83ab-899cea4d5a94'), editable=False, primary_key=True, serialize=False),
        ),
    ]
