# Generated by Django 5.1.1 on 2024-10-12 08:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('89750730-6b1c-4710-b9ae-333e62b2de55'), editable=False, primary_key=True, serialize=False),
        ),
    ]
