# Generated by Django 5.1.1 on 2024-10-13 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e1916945-1125-4ab0-8b34-3a772c86a35d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
